using System.Text.RegularExpressions;

namespace RdfTableEditor.Model.Schema;

public static class TableRegistry
{
    // Map filename patterns to schemas
    private static readonly List<(Regex pattern, TableSchema schema)> _schemas = new()
    {
        // TextAll container (chunks of: [int TableType][int PayloadSize][Payload])
        (new Regex("text_?all", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "TextAll",
                hasMargin: false,
                fields: new []
                {
                    new Field("TableType", ScalarType.U32),
                    new Field("PayloadSize", ScalarType.U32)
                })),
        // Quest Text (variable-length UTF-16 strings per row)
    (new Regex("quest_?text", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "QuestText",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
            // Variable-length UTF-16 text, WORD length prefix
            new Field("Quest_Text", ScalarType.WStringVar)
                })),
        // CharTitle
        (new Regex("char.?title", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "CharTitle",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("NameIndex", ScalarType.U32),
                    new Field("ContentsType", ScalarType.U8),
                    new Field("RepresentationType", ScalarType.U8),
                    new Field("BoneName", ScalarType.WStringFixed, length: 0x200 + 1),
                    new Field("EffectName", ScalarType.WStringFixed, length: 0x200 + 1),
                    new Field("EffectSound", ScalarType.WStringFixed, length: 0x200 + 1),
                    new Field("SystemEffectTblidx", ScalarType.U32, length: 3, isArray: true),
                    new Field("SystemEffectType", ScalarType.U8, length: 3, isArray: true),
                    new Field("SystemEffectValue", ScalarType.Double, length: 3, isArray: true)
                })),

        // ChatCommand
        (new Regex("chat.?command", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "ChatCommand",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("Validity_Able", ScalarType.Bool),
                    new Field("Action_Animation_Index", ScalarType.U16),
                    new Field("Chat_Command", ScalarType.U32, length: 8, isArray: true)
                }))
        ,
        // NPC (sTBLDAT -> sCHAR_TBLDAT -> sBOT_TBLDAT -> sNPC_TBLDAT)
    (new Regex("Table_?NPC_?Data|npc_data|\\bnpc\\b|table_?npc|_table_?npc", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "NPC",
                hasMargin: true,
                fields: new []
                {
                    // sTBLDAT
                    new Field("Tblidx", ScalarType.U32),
                    // sCHAR_TBLDAT
                    new Field("Basic_LP", ScalarType.U32),
                    new Field("Basic_EP", ScalarType.U16),
                    new Field("Basic_Physical_Defence", ScalarType.U16),
                    new Field("Basic_Energy_Defence", ScalarType.U16),
                    new Field("Str", ScalarType.U16),
                    new Field("Con", ScalarType.U16),
                    new Field("Foc", ScalarType.U16),
                    new Field("Dex", ScalarType.U16),
                    new Field("Sol", ScalarType.U16),
                    new Field("Eng", ScalarType.U16),
                    new Field("Scale", ScalarType.Float),
                    new Field("Attack_Speed_Rate", ScalarType.U16),
                    new Field("Attack_Type", ScalarType.U8),
                    new Field("Attack_Range", ScalarType.Float),
                    new Field("Basic_Attack_Rate", ScalarType.U16),
                    new Field("Basic_Dodge_Rate", ScalarType.U16),
                    new Field("Basic_Block_Rate", ScalarType.U16),
                    new Field("Basic_Curse_Success_Rate", ScalarType.U16),
                    new Field("Basic_Curse_Tolerance_Rate", ScalarType.U16),
                    new Field("Radius", ScalarType.Float),
                    new Field("Basic_Aggro_Point", ScalarType.U16),
                    // sBOT_TBLDAT
                    new Field("Validity_Able", ScalarType.Bool),
                    new Field("Name", ScalarType.U32),
                    new Field("NameText", ScalarType.WStringFixed, length: 40 + 1),
                    new Field("Model", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Level", ScalarType.U8),
                    new Field("Grade", ScalarType.U8),
                    new Field("Ai_Bit_Flag", ScalarType.U32),
                    new Field("LP_Regeneration", ScalarType.U16),
                    new Field("EP_Regeneration", ScalarType.U16),
                    new Field("Attack_Animation_Quantity", ScalarType.U8),
                    new Field("Battle_Attribute", ScalarType.U8),
                    new Field("Basic_Physical_Offence", ScalarType.U16),
                    new Field("Basic_Energy_Offence", ScalarType.U16),
                    new Field("Walk_Speed_Origin", ScalarType.Float),
                    new Field("Walk_Speed", ScalarType.Float),
                    new Field("Run_Speed_Origin", ScalarType.Float),
                    new Field("Run_Speed", ScalarType.Float),
                    new Field("Radius_X", ScalarType.Float),
                    new Field("Radius_Z", ScalarType.Float),
                    new Field("Sight_Range", ScalarType.U16),
                    new Field("Scan_Range", ScalarType.U16),
                    new Field("Use_Skill_Time", ScalarType.U16, length: 8, isArray: true),
                    new Field("Use_Skill_Tblidx", ScalarType.U32, length: 8, isArray: true),
                    new Field("Use_Skill_Basis", ScalarType.U8, length: 8, isArray: true),
                    new Field("Use_Skill_LP", ScalarType.U16, length: 8, isArray: true),
                    new Field("Visible_Sight_Range", ScalarType.U8),
                    new Field("Camera_Bone_Name", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Attack_Cool_Time", ScalarType.U16),
                    new Field("Fly_Height", ScalarType.Float),
                    new Field("NameTextAnsi", ScalarType.AnsiStringFixed, length: 40 + 1),
                    new Field("Spawn_Animation", ScalarType.Bool),
                    new Field("Dialog_Group", ScalarType.U32),
                    new Field("ILLust", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Alliance_Idx", ScalarType.U32),
                    new Field("Aggro_Max_Count", ScalarType.U16),
                    new Field("NpcAttributeFlag", ScalarType.U32),
                    new Field("StomachacheDefence", ScalarType.U16),
                    new Field("PoisonDefence", ScalarType.U16),
                    new Field("BleedDefence", ScalarType.U16),
                    new Field("BurnDefence", ScalarType.U16),
                    // sNPC_TBLDAT
                    new Field("NpcType", ScalarType.U8),
                    new Field("Job", ScalarType.U8),
                    new Field("Function_Bit_Flag", ScalarType.U32),
                    new Field("Dialog_Script_Index", ScalarType.U32),
                    new Field("Merchant_Tblidx", ScalarType.U32, length: 6, isArray: true),
                    new Field("Status_Transform_Tblidx", ScalarType.U32),
                    new Field("Contents_Tblidx", ScalarType.U32),
                    new Field("Unknown_Word", ScalarType.U16),
                    new Field("Unknown_Dword2", ScalarType.U32),
                    new Field("Unknown_Dword3", ScalarType.U32)
                }))
        ,
        // MOB (sTBLDAT -> sCHAR_TBLDAT -> sBOT_TBLDAT -> sMOB_TBLDAT)
    (new Regex("Table_?MOB_?Data|mob_data|\\bmob\\b|table_?mob|_table_?mob", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "MOB",
                hasMargin: true,
                fields: new []
                {
                    // sTBLDAT
                    new Field("Tblidx", ScalarType.U32),
                    // sCHAR_TBLDAT
                    new Field("Basic_LP", ScalarType.U32),
                    new Field("Basic_EP", ScalarType.U16),
                    new Field("Basic_Physical_Defence", ScalarType.U16),
                    new Field("Basic_Energy_Defence", ScalarType.U16),
                    new Field("Str", ScalarType.U16),
                    new Field("Con", ScalarType.U16),
                    new Field("Foc", ScalarType.U16),
                    new Field("Dex", ScalarType.U16),
                    new Field("Sol", ScalarType.U16),
                    new Field("Eng", ScalarType.U16),
                    new Field("Scale", ScalarType.Float),
                    new Field("Attack_Speed_Rate", ScalarType.U16),
                    new Field("Attack_Type", ScalarType.U8),
                    new Field("Attack_Range", ScalarType.Float),
                    new Field("Basic_Attack_Rate", ScalarType.U16),
                    new Field("Basic_Dodge_Rate", ScalarType.U16),
                    new Field("Basic_Block_Rate", ScalarType.U16),
                    new Field("Basic_Curse_Success_Rate", ScalarType.U16),
                    new Field("Basic_Curse_Tolerance_Rate", ScalarType.U16),
                    new Field("Radius", ScalarType.Float),
                    new Field("Basic_Aggro_Point", ScalarType.U16),
                    // sBOT_TBLDAT base
                    new Field("Validity_Able", ScalarType.Bool),
                    new Field("Name", ScalarType.U32),
                    new Field("NameText", ScalarType.WStringFixed, length: 40 + 1),
                    new Field("Model", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Level", ScalarType.U8),
                    new Field("Grade", ScalarType.U8),
                    new Field("Ai_Bit_Flag", ScalarType.U32),
                    new Field("LP_Regeneration", ScalarType.U16),
                    new Field("EP_Regeneration", ScalarType.U16),
                    new Field("Attack_Animation_Quantity", ScalarType.U8),
                    new Field("Battle_Attribute", ScalarType.U8),
                    new Field("Basic_Physical_Offence", ScalarType.U16),
                    new Field("Basic_Energy_Offence", ScalarType.U16),
                    new Field("Walk_Speed_Origin", ScalarType.Float),
                    new Field("Walk_Speed", ScalarType.Float),
                    new Field("Run_Speed_Origin", ScalarType.Float),
                    new Field("Run_Speed", ScalarType.Float),
                    new Field("Radius_X", ScalarType.Float),
                    new Field("Radius_Z", ScalarType.Float),
                    new Field("Sight_Range", ScalarType.U16),
                    new Field("Scan_Range", ScalarType.U16),
                    new Field("Use_Skill_Time", ScalarType.U16, length: 8, isArray: true),
                    new Field("Use_Skill_Tblidx", ScalarType.U32, length: 8, isArray: true),
                    new Field("Use_Skill_Basis", ScalarType.U8, length: 8, isArray: true),
                    new Field("Use_Skill_LP", ScalarType.U16, length: 8, isArray: true),
                    new Field("Visible_Sight_Range", ScalarType.U8),
                    new Field("Camera_Bone_Name", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Attack_Cool_Time", ScalarType.U16),
                    new Field("Fly_Height", ScalarType.Float),
                    new Field("NameTextAnsi", ScalarType.AnsiStringFixed, length: 40 + 1),
                    new Field("Spawn_Animation", ScalarType.Bool),
                    new Field("Dialog_Group", ScalarType.U32),
                    new Field("ILLust", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Alliance_Idx", ScalarType.U32),
                    new Field("Aggro_Max_Count", ScalarType.U16),
                    new Field("NpcAttributeFlag", ScalarType.U32),
                    new Field("StomachacheDefence", ScalarType.U16),
                    new Field("PoisonDefence", ScalarType.U16),
                    new Field("BleedDefence", ScalarType.U16),
                    new Field("BurnDefence", ScalarType.U16),
                    // sMOB_TBLDAT extras
                    new Field("MobGroup", ScalarType.U32),
                    new Field("Mob_Kind", ScalarType.U16),
                    new Field("Drop_Zenny", ScalarType.U32),
                    new Field("Drop_Zenny_Rate", ScalarType.Float),
                    new Field("Exp", ScalarType.U32),
                    new Field("Mob_Type", ScalarType.U8),
                    new Field("drop_Item_Tblidx", ScalarType.U32),
                    new Field("Size", ScalarType.Bool),
                    new Field("TMQPoint", ScalarType.U16),
                    new Field("dropQuestTblidx", ScalarType.U32),
                    // Interleaved big bag drops (TBLIDX, BYTE, BYTE) * 3
                    new Field("idxBigBag1", ScalarType.U32),
                    new Field("DropRate1", ScalarType.U8),
                    new Field("TryCount1", ScalarType.U8),
                    new Field("idxBigBag2", ScalarType.U32),
                    new Field("DropRate2", ScalarType.U8),
                    new Field("TryCount2", ScalarType.U8),
                    new Field("idxBigBag3", ScalarType.U32),
                    new Field("DropRate3", ScalarType.U8),
                    new Field("TryCount3", ScalarType.U8),
                    new Field("Unknown", ScalarType.U32),
                    new Field("UnknownB1", ScalarType.U8),
                    new Field("UnknownB2", ScalarType.U8),
                    new Field("Show_Name", ScalarType.Bool),
                    new Field("SightAngle", ScalarType.U16),
                    new Field("Immunity_Bit_Flag", ScalarType.U32),
                    new Field("IsDragonBallDrop", ScalarType.Bool),
                    new Field("MonsterClass", ScalarType.U16),
                    new Field("UseRace", ScalarType.U16),
                    new Field("RewardExpRate", ScalarType.Float),
                    new Field("RewardZennyRate", ScalarType.Float),
                    new Field("FormulaOffset", ScalarType.U32),
                    new Field("SettingRate_LP", ScalarType.Float),
                    new Field("SettingRate_LPRegen", ScalarType.Float),
                    new Field("SettingRate_PhyOffence", ScalarType.Float),
                    new Field("SettingRate_EngOffence", ScalarType.Float),
                    new Field("SettingRate_PhyDefence", ScalarType.Float),
                    new Field("SettingRate_EngDefence", ScalarType.Float),
                    new Field("SettingRate_AttackRate", ScalarType.Float),
                    new Field("SettingRate_DodgeRate", ScalarType.Float),
                    new Field("SettingPhyOffenceRate", ScalarType.Float),
                    new Field("SettingEngOffenceRate", ScalarType.Float),
                    new Field("SettingRate_Defence_Role", ScalarType.Float)
        })),
    // ChattingFilter (example: Valid, ResultCode)
        (new Regex("chat.?filter", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "ChatFilter",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("Validity_Able", ScalarType.Bool),
                    new Field("ResultCode", ScalarType.U32)
        })),
    // SystemEffect
    (new Regex("table_?system.?effect|_table_?system.?effect|system.?effect", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "SystemEffect",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("Name", ScalarType.WStringFixed, length: 40 + 1),
                    new Field("Effect_Type", ScalarType.U8),
                    new Field("Active_Effect_Type", ScalarType.U8),
                    new Field("Effect_Info_Text", ScalarType.U32),
                    new Field("Keep_Effect_Name", ScalarType.U32),
                    new Field("Target_Effect_Position", ScalarType.U8),
                    new Field("Success_Effect_Name", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Success_Projectile_Type", ScalarType.U8),
                    new Field("Success_Effect_Position", ScalarType.U8),
                    new Field("Success_End_Effect_Name", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("End_Effect_Position", ScalarType.U8),
                    new Field("Keep_Animation_Index", ScalarType.U16),
                    new Field("EffectCode", ScalarType.U32)
        })),
        // UseItem
        (new Regex("Use_?Item|table_?use_?item|_table_?use_?item", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "UseItem",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("Use_Item_Active_Type", ScalarType.U8),
                    new Field("Buff_Group", ScalarType.U8),
                    new Field("BuffKeepType", ScalarType.U8),
                    new Field("Cool_Time_Bit_Flag", ScalarType.U32),
                    new Field("Function_Bit_Flag", ScalarType.U16),
                    new Field("Use_Restriction_Rule_Bit_Flag", ScalarType.U32),
                    new Field("Use_Allow_Rule_Bit_Flag", ScalarType.U32),
                    new Field("Appoint_Target", ScalarType.U8),
                    new Field("Apply_Target", ScalarType.U8),
                    new Field("Apply_Target_Index", ScalarType.U32),
                    new Field("Apply_Target_Max", ScalarType.U8),
                    new Field("Apply_Range", ScalarType.U8),
                    new Field("Apply_Area_Size_1", ScalarType.U8),
                    new Field("Apply_Area_Size_2", ScalarType.U8),
                    new Field("Need_State_Bit_Flag", ScalarType.U16),
                    new Field("System_Effect", ScalarType.U32, length: 2, isArray: true),
                    new Field("System_Effect_Type", ScalarType.U8, length: 2, isArray: true),
                    new Field("System_Effect_Value", ScalarType.Double, length: 2, isArray: true),
                    new Field("Require_LP", ScalarType.U32),
                    new Field("Require_EP", ScalarType.U16),
                    new Field("Require_RP_Ball", ScalarType.U8),
                    new Field("Casting_Time", ScalarType.Float),
                    new Field("CastingTimeInMilliSecs", ScalarType.U32),
                    new Field("Cool_Time", ScalarType.U32),
                    new Field("CoolTimeInMilliSecs", ScalarType.U32),
                    new Field("Keep_Time", ScalarType.U32),
                    new Field("KeepTimeInMilliSecs", ScalarType.U32),
                    new Field("Keep_Effect", ScalarType.Bool),
                    new Field("Use_Range_Min", ScalarType.U8),
                    new Field("Use_Range_Min_F", ScalarType.Float),
                    new Field("Use_Range_Max", ScalarType.U8),
                    new Field("Use_Range_Max_F", ScalarType.Float),
                    new Field("Use_Info_Text", ScalarType.U32),
                    new Field("Casting_Effect", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Action_Effect", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Casting_Animation_Start", ScalarType.U16),
                    new Field("Casting_Animation_Loop", ScalarType.U16),
                    new Field("Action_Animation_Index", ScalarType.U16),
                    new Field("Action_Loop_Animation_Index", ScalarType.U16),
                    new Field("Action_End_Animation_Index", ScalarType.U16),
                    new Field("CastingEffectPosition", ScalarType.U8),
                    new Field("ActionEffectPosition", ScalarType.U8),
                    new Field("useWorldTblidx", ScalarType.U32),
                    new Field("UseLoc_X", ScalarType.Float),
                    new Field("UseLoc_Z", ScalarType.Float),
                    new Field("UseLoc_Radius", ScalarType.Float),
                    new Field("RequiredQuestID", ScalarType.U32)
                })),
        // ServerConfig (name/value pairs packed via pack(4))
        (new Regex("server_?config", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "ServerConfig",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("Name", ScalarType.WStringVar),
                    new Field("Value0", ScalarType.WStringVar),
                    new Field("Value1", ScalarType.WStringVar),
                    new Field("Value2", ScalarType.WStringVar),
                    new Field("Value3", ScalarType.WStringVar),
                    new Field("Value4", ScalarType.WStringVar),
                    new Field("Value5", ScalarType.WStringVar),
                    new Field("Value6", ScalarType.WStringVar),
                    new Field("Value7", ScalarType.WStringVar),
                    new Field("Value8", ScalarType.WStringVar),
                    new Field("Value9", ScalarType.WStringVar)
                })),
        // Merchant (full)
        (new Regex("merchant_data|table_?merchant|_table_?merchant", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "Merchant",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("NameText", ScalarType.WStringFixed, length: 16 + 1),
                    new Field("Sell_Type", ScalarType.U8),
                    new Field("Tab_Name", ScalarType.U32),
                    new Field("NeedMileage", ScalarType.U32),
                    new Field("Item_Tblidx", ScalarType.U32, length: 36, isArray: true),
                    new Field("NeedItemTblidx", ScalarType.U32, length: 36, isArray: true),
                    new Field("NeedItemStack", ScalarType.U8, length: 36, isArray: true),
                    new Field("NeedZenny", ScalarType.U32, length: 36, isArray: true)
                })),
        // Spawn MOB/NPC/OBJECT (we currently only show raw headers to allow opening; full schemas TBD)
        (new Regex("spawn_?mob|Spawn_?MOB", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "SpawnMob",
                hasMargin: false,
                fields: new []
                {
                    new Field("WorldOrZone", ScalarType.U32),
                    new Field("Unknown1", ScalarType.U32),
                })),
        (new Regex("spawn_?npc|Spawn_?NPC", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "SpawnNpc",
                hasMargin: false,
                fields: new []
                {
                    new Field("WorldOrZone", ScalarType.U32),
                    new Field("Unknown1", ScalarType.U32),
                })),
        (new Regex("spawn_?object|Spawn_?Object", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "SpawnObject",
                hasMargin: false,
                fields: new []
                {
                    new Field("WorldOrZone", ScalarType.U32),
                    new Field("Unknown1", ScalarType.U32),
                })),
    // Skill (partial schema)
    (new Regex("table_?skill|_table_?skill|\\bskill\\b", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "Skill",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("Skill_Name", ScalarType.U32),
                    new Field("NameText", ScalarType.WStringFixed, length: 40 + 1),
                    new Field("Validity_Able", ScalarType.Bool),
                    new Field("PC_Class_Bit_Flag", ScalarType.U32),
                    new Field("Class_Type", ScalarType.U8),
                    new Field("Skill_Class", ScalarType.U8),
                    new Field("Skill_Type", ScalarType.U8),
                    new Field("Skill_Active_Type", ScalarType.U8),
                    new Field("Buff_Group", ScalarType.U8),
                    new Field("Slot_Index", ScalarType.U8),
                    new Field("Skill_Grade", ScalarType.U8),
                    new Field("Function_Bit_Flag", ScalarType.U32),
                    new Field("Appoint_Target", ScalarType.U8),
                    new Field("Apply_Target", ScalarType.U8),
                    new Field("Apply_Target_Max", ScalarType.U8),
                    new Field("Apply_Range", ScalarType.U8),
                    new Field("Apply_Area_Size_1", ScalarType.U8),
                    new Field("Apply_Area_Size_2", ScalarType.U8),
                    new Field("Skill_Effect", ScalarType.U32, length: 2, isArray: true),
                    new Field("Skill_Effect_Type", ScalarType.U8, length: 2, isArray: true),
                    new Field("Skill_Effect_Value", ScalarType.Double, length: 2, isArray: true),
                    new Field("Additional_Aggro_Point", ScalarType.U32),
                    new Field("RpEffect", ScalarType.U8, length: 8, isArray: true),
                    new Field("RpEffectValue", ScalarType.Float, length: 8, isArray: true),
                    new Field("Require_Train_Level", ScalarType.U8),
                    new Field("Require_Zenny", ScalarType.U32),
                    new Field("Next_Skill_Train_Exp", ScalarType.U16),
                    new Field("RequireSP", ScalarType.U16),
                    new Field("SelfTrain", ScalarType.Bool),
                    new Field("Require_Skill_Tblidx_Min_1", ScalarType.U32),
                    new Field("Require_Skill_Tblidx_Max_1", ScalarType.U32),
                    new Field("Require_Skill_Tblidx_Min_2", ScalarType.U32),
                    new Field("Require_Skill_Tblidx_Max_2", ScalarType.U32),
                    new Field("Root_Skill", ScalarType.U32),
                    new Field("Require_Epuip_Slot_Type", ScalarType.U8),
                    new Field("Require_Item_Type", ScalarType.U8),
                    new Field("Icon_Name", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Require_LP", ScalarType.U32),
                    new Field("Require_EP", ScalarType.U16),
                    new Field("Require_RP_Ball", ScalarType.U8),
                    new Field("Casting_Time", ScalarType.Float),
                    new Field("CastingTimeInMilliSecs", ScalarType.U32),
                    new Field("Cool_Time", ScalarType.U16),
                    new Field("CoolTimeInMilliSecs", ScalarType.U32),
                    new Field("Keep_Time", ScalarType.U16),
                    new Field("KeepTimeInMilliSecs", ScalarType.U32),
                    new Field("Keep_Effect", ScalarType.Bool),
                    new Field("Use_Range_Min_By", ScalarType.U8),
                    new Field("Use_Range_Min", ScalarType.Float),
                    new Field("Use_Range_Max_By", ScalarType.U8),
                    new Field("Use_Range_Max", ScalarType.Float),
                    new Field("Note", ScalarType.U32),
                    new Field("NextSkillTblidx", ScalarType.U32),
                    new Field("DefaultDisplayOff", ScalarType.Bool),
                    new Field("Animation_Time", ScalarType.U32),
                    new Field("Casting_Animation_Start", ScalarType.U16),
                    new Field("Casting_Animation_Loop", ScalarType.U16),
                    new Field("Action_Animation_Index", ScalarType.U16),
                    new Field("Action_Loop_Animation_Index", ScalarType.U16),
                    new Field("Action_End_Animation_Index", ScalarType.U16),
                    new Field("Dash_Able", ScalarType.Bool),
                    new Field("Transform_Use_Info_Bit_Flag", ScalarType.U32),
                    new Field("Success_Rate", ScalarType.Float),
                    new Field("PC_Class_Change", ScalarType.U8),
                    new Field("Use_Type", ScalarType.U8),
                    new Field("Skill_Group", ScalarType.U8),
                    new Field("Require_VP", ScalarType.U32),
                    new Field("Use_Restriction_Rule_Bit_Flag", ScalarType.U32)
        })),
    // Item (partial schema)
    (new Regex("\\btable_?item|_table_?item|\\bitem\\b|o_table_item_data", RegexOptions.IgnoreCase | RegexOptions.Compiled),
            new TableSchema(
                name: "Item",
                hasMargin: true,
                fields: new []
                {
                    new Field("Tblidx", ScalarType.U32),
                    new Field("Validity_Able", ScalarType.Bool),
                    new Field("Name", ScalarType.U32),
                    // C++ uses 40+1 WCHARs for NameText in many DBO builds; use 41 to keep correct alignment
                    new Field("NameText", ScalarType.WStringFixed, length: 40 + 1),
            new Field("Icon_Name", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Model_Type", ScalarType.U8),
            new Field("Model", ScalarType.AnsiStringFixed, length: 32 + 1),
            new Field("Sub_Weapon_Act_Model", ScalarType.AnsiStringFixed, length: 32 + 1),
                    new Field("Item_Type", ScalarType.U8),
                    new Field("Equip_Type", ScalarType.U8),
                    new Field("Equip_Slot_Type_Bit_Flag", ScalarType.U32),
                    new Field("Function_Bit_Flag", ScalarType.U16),
                    new Field("Max_Stack", ScalarType.U8),
                    new Field("Rank", ScalarType.U8),
                    new Field("Weight", ScalarType.U32),
                    new Field("Cost", ScalarType.U32),
                    new Field("Sell_Price", ScalarType.U32),
                    new Field("Durability", ScalarType.U8),
                    new Field("Durability_Count", ScalarType.U8),
                    new Field("Battle_Attribute", ScalarType.U8),
                    new Field("Physical_Offence", ScalarType.U16),
                    new Field("Energy_Offence", ScalarType.U16),
                    new Field("Physical_Defence", ScalarType.U16),
                    new Field("Energy_Defence", ScalarType.U16),
                    new Field("Attack_Range_Bonus", ScalarType.Float),
                    new Field("Attack_Speed_Rate", ScalarType.U16),
                    new Field("Need_Min_Level", ScalarType.U8),
                    new Field("Need_Max_Level", ScalarType.U8),
                    new Field("Need_Class_Bit_Flag", ScalarType.U32),
                    new Field("Need_Gender_Bit_Flag", ScalarType.U32),
                    new Field("Class_Special", ScalarType.U8),
                    new Field("Race_Special", ScalarType.U8),
                    new Field("Need_Str", ScalarType.U16),
                    new Field("Need_Con", ScalarType.U16),
                    new Field("Need_Foc", ScalarType.U16),
                    new Field("Need_Dex", ScalarType.U16),
                    new Field("Need_Sol", ScalarType.U16),
                    new Field("Need_Eng", ScalarType.U16),
                    new Field("set_Item_Tblidx", ScalarType.U32),
                    new Field("Note", ScalarType.U32),
                    new Field("Bag_Size", ScalarType.U8),
                    new Field("Scouter_Watt", ScalarType.U16),
                    new Field("Scouter_MaxPower", ScalarType.U32),
                    new Field("Scouter_Parts_Type1", ScalarType.U8),
                    new Field("Scouter_Parts_Type2", ScalarType.U8),
                    new Field("Scouter_Parts_Type3", ScalarType.U8),
                    new Field("Scouter_Parts_Type4", ScalarType.U8),
                    new Field("Use_Item_Tblidx", ScalarType.U32),
                    new Field("IsCanHaveOption", ScalarType.Bool),
                    new Field("Item_Option_Tblidx", ScalarType.U32),
                    new Field("ItemGroup", ScalarType.U8),
                    new Field("Charm_Tblidx", ScalarType.U32),
                    new Field("CostumeHideBitFlag", ScalarType.U16),
                    new Field("NeedItemTblidx", ScalarType.U32),
                    new Field("CommonPoint", ScalarType.U32),
                    new Field("CommonPointType", ScalarType.U8),
                    new Field("NeedFunction", ScalarType.U8),
                    new Field("UseDurationMax", ScalarType.U32),
                    new Field("DurationType", ScalarType.U8),
                    new Field("contentsTblidx", ScalarType.U32),
                    new Field("DurationGroup", ScalarType.U32),
                    new Field("DropLevel", ScalarType.U8),
                    new Field("enchantRateTblidx", ScalarType.U32),
                    new Field("excellentTblidx", ScalarType.U32),
                    new Field("rareTblidx", ScalarType.U32),
                    new Field("legendaryTblidx", ScalarType.U32),
                    new Field("CreateSuperiorAble", ScalarType.Bool),
                    new Field("CreateExcellentAble", ScalarType.Bool),
                    new Field("CreateRareAble", ScalarType.Bool),
                    new Field("CreateLegendaryAble", ScalarType.Bool),
                    new Field("RestrictType", ScalarType.U8),
                    new Field("Attack_Physical_Revision", ScalarType.Float),
                    new Field("Attack_Energy_Revision", ScalarType.Float),
                    new Field("Defence_Physical_Revision", ScalarType.Float),
                    new Field("Defence_Energy_Revision", ScalarType.Float),
                    new Field("TmpTabType", ScalarType.U8),
                    new Field("IsCanRenewal", ScalarType.Bool),
                    new Field("Disassemble_Bit_Flag", ScalarType.U16),
                    new Field("DisassembleNormalMin", ScalarType.U8),
                    new Field("DisassembleNormalMax", ScalarType.U8),
                    new Field("DisassembleUpperMin", ScalarType.U8),
                    new Field("DisassembleUpperMax", ScalarType.U8),
                    new Field("DropVisual", ScalarType.U8),
                    new Field("UseDisassemble", ScalarType.U8)
                }))
    };

    public static TableSchema? FromFilename(string path)
    {
        foreach (var (pattern, schema) in _schemas)
        {
            if (pattern.IsMatch(path)) return schema;
        }
        return null;
    }
}
